version: "3.6"
services:
  
  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    container_name: zookeeper
    ports:
      - 2181:2181
    environment:
      - ZOOKEEPER_CLIENT_PORT: 2181
  
  kafka:
    image: confluentinc/cp-kafka:latest
    depends_on:
      - zookeeper
    ports:
      - 9092:9092
    environment:
      - KAFKA_BROKER_ID: 1
      - KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      - KAFKA_ADVERTISED_LISTENERS: INTERNAL://kafka:29092,EXTERNAL://kafka:9092
      - KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT
      - KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
      - KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
  
  shop-api:
    image: jeffersonpcinfo/shop-api
    container_name: shop-api
    ports:
      - 8080:8080
    depends_on:
      - kafka
  
  shop-python:
    image: jeffersonpcinfo/shop-python
    container_name: shop-python
    ports:
      - 5000:5000
    depends_on:
      - kafka